name: todo_work_sessions
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0 
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.5.1
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.3
  package_info_plus: ^8.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  mockito: ^5.4.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

flutter_native_splash:
  color: "#FFFFFF" 
  image: assets/images/logo.png 
  android_gravity: center
  ios_content_mode: center
